// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mvc.Models;

public partial class Department
{
    public int DepartmentId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}